apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: {{ .Values.secrets.dbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}
  DB_NAME: {{ .Values.secrets.dbName | b64enc }}
  DB_HOST: {{ .Values.secrets.dbHost | b64enc }}
